# Generated by Django 3.0.5 on 2020-04-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('question', models.TextField(max_length=400)),
                ('priority', models.CharField(choices=[('1', 'Low'), ('2', 'Mediun'), ('3', 'Hihg')], max_length=1)),
            ],
        ),
    ]
