# Generated by Django 3.0.5 on 2020-04-23 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('brand', models.CharField(choices=[('Niagara', 'Niagara'), ('Phoenix', 'Phoenix'), ('Giant', 'Giant')], max_length=20)),
                ('description', models.TextField(max_length=400)),
            ],
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'The Question', 'verbose_name_plural': 'Peoples Questions'},
        ),
        migrations.AlterField(
            model_name='question',
            name='priority',
            field=models.CharField(choices=[('L', 'Low'), ('M', 'Mediun'), ('H', 'High')], max_length=1),
        ),
    ]
